### ISSUE TITLE
ときはなたれしフーパ

### ISSUE THREAD

**Issue by k-yone** [towakey/pokedex#11]
有益なjsonデータありがとうございます。個人プロジェクトで使わせていただいてます。
フーパのときはなたれし姿が載っていないのでご報告させていただきます。
フォルムチェンジとは別扱いで載せない方針でしたら無視していただければ・・・！

**Comment by towakey** [comment]
ご利用ありがとうございます。
完全に追加わすれです…。
追加しましたので最新コミット版をご使用ください。
