### ISSUE TITLE
一部ポケモンの重さデータに誤り

### ISSUE THREAD

**Issue by roodni** [towakey/pokedex#2]
第4世代バトルステージに出現するポケモンの重さを調べていたところ、
スボミー・ロズレイド・リーシャン・エルレイド・ジバコイル・ダイノーズ・ドサイドン
の重さが間違っていることに気が付きました。

例: スボミー(1.2kg)
https://github.com/towakey/pokedex/blob/5a49b7b3e86bd216322233cd9abad0f5592a0be4/pokedex/pokedex.json#L6719-L6733

私は第4世代バトルステージの出現ポケモンしか調べていないので、他にも重さに誤りがあるポケモンがいるかもしれません。

**Comment by towakey** [comment]
ありがとうございます。
ご指摘のポケモンの重さは修正しました。
